# -*- coding: utf-8 -*-
"""LVADSUSR195_Venkatsundhar-sp_LAB-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwqInXENYwy8q00wVBu3mJTPhD109JOT
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,accuracy_score,f1_score,precision_score,recall_score,classification_report,confusion_matrix
from sklearn.preprocessing import MinMaxScaler
import xgboost as xgb
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('/content/sample_data/Mall_Customers.csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df.dropna(inplace=True)











