# -*- coding: utf-8 -*-
"""LVADSUSR195_Venkatsundhar__SP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvWj5uWFKTUn-ePPga7V6W22w4OCZZD1

4403 LVADSUSR195 VENKATSUNDHAR SP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""QN-1"""

#1
#1a
df = pd.read_csv('/content/Final Dataset - IPL.csv')
df.head(5)

#1b
df.info()
df.describe()

'''
The given ipl dataset has 74 rows and 20 columns
Dim - 74*20
Has columns with many datatypes like int64,object(string)
involving both numerical and categorical.

'''

#1b
print(df.isnull().sum())
# From this we can conclude that the dataset doesnt have any
# missing values

"""QN-2"""

#2a
print(df.isnull().sum())
'''
By using the isnull() function we can see that the
dataset doesnt have any missing values and is clean
therefore no need to drop.

'''

#2b
df.duplicated()

#2b
df.drop_duplicates()

'''
Output of drop duplicates returns
74 rows (Same size as df) hence confirming
there are no duplictes in the dataset.

'''

"""QN-3"""

#3
num_data = df[['match_id','first_ings_score','first_ings_wkts',
               'second_ings_score','second_ings_wkts','margin','highscore']]
mean = num_data.mean()
print("Mean:\n",mean)
median = num_data.median()
print("\nMedian:\n",median)
mode = num_data.mode()
print("\nMode:\n",mode)
variance = num_data.var()
print("\nVariance:\n",variance)
std = num_data.std()
print("\nStandard Deviation:\n",std)
range = num_data.max()-num_data.min()
print("\nRange:\n",range)

'''
These depict the central tendencies and variability of the data
'''

"""QN-4"""

#4 HISTOGRAM
plt.title("Histogram of first innings score")
sns.histplot(df,x='first_ings_score')
plt.show()

#4 SCATTER PLOT
plt.title("A comaprison of First innings wkts and runs scored")
sns.scatterplot(df,x='first_ings_wkts',y='first_ings_score')
plt.show()

#4 Box plot
plt.title('High scores in ipl 2022')
sns.boxplot(df,x='highscore')
plt.show()
'''
Quinton's score of 140 is the outlier in the dataset
'''

#4 BAR CHART
dff = df.sort_values(by='highscore',ascending=False)
dff_head = dff.head(3)
plt.title("Top scorers of ipl 2022")
sns.barplot(dff_head,x='top_scorer',y='highscore')
plt.show()

"""QN-5"""

#5
cor = df[['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts']]
D = cor.corr()
plt.title("How wickets affect team scores")
sns.heatmap(D,annot=True)
plt.show()
'''
First innings score has a direct impact on 2nd innings score as
it puishes teams to chase the target and wickets have inverse
relation to team scores
'''

"""QN-6"""

#6
plt.figure(figsize=(12,5))
sns.boxplot(df)

"""QN-7"""

#7
dff = df.groupby(['match_winner','venue']).aggregate({'venue':'count'})
print(dff)
print(dff[dff['venue']==dff['venue'].max()])

#7
from matplotlib import pyplot as plt
dff['venue'].plot(kind='line', figsize=(8, 4), title='venue')
plt.gca().spines[['top', 'right']].set_visible(False)

'''
As we see in the numerical dataset, we have some outliers in almost every column stating the unpredictability of the game of cricket.
Mainly in the first,second innings score and high score had few possible outliers which can affect the data but
these specific statistics might get more common in future as these outliers are gonna become common and become a part of data
also these are the things that define the game hence removing these wont be a good option
'''

"""QN-8"""

#8
potm = df.groupby('player_of_the_match').aggregate({'player_of_the_match':'count'})
print(potm)
print(potm[potm['player_of_the_match']==potm['player_of_the_match'].max()])

#8
corrr = df[['first_ings_score','second_ings_score','highscore']]
Dd = corrr.corr()
plt.title("High score vs Innings score")
sns.heatmap(Dd,annot=True)
plt.show()

#8
'''
Players like kuldeep yadav, jos buttler won the most player of
the matches as the pitch suited them and their respective
teams have won more games in the stadium as shown in qn 7
As players score highly, that has a significantly positive impact
on their respective sides as shown in the heatmap.

'''

"""QN-9"""

#9
plt.figure(figsize=(12,5))
sns.boxplot(df)

'''
As we see in the numerical dataset, we have some outliers in almost every column stating the unpredictability of the game of cricket.
Mainly in the first,second innings score and high score had few possible outliers which can affect the data but
these specific statistics might get more common in future as these outliers are gonna become common and become a part of data
also these are the things that define the game hence removing these wont be a good option
'''

#9
from matplotlib import pyplot as plt
dff['venue'].plot(kind='line', figsize=(8, 4), title='venue')
plt.gca().spines[['top', 'right']].set_visible(False)

'''
As we see Bangalore and Delhi has won more games in mumbai.
'''

